name: saws
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_fonts:  0.2.0
  google_maps_flutter:
  dots_indicator: ^0.0.4
  flutter_statusbarcolor: 0.2.3
  flutter_rating_bar: 3.0.1+1
  simple_animations: 1.3.8
  percent_indicator: ^2.1.1
  snaplist:
  flutter_svg:
  flutter_slidable:
  flutter_staggered_grid_view:
  auto_size_text:
  flutter_staggered_animations:
  nb_utils: 3.0.3
  flutter_multi_carousel: ^1.0.0
  intl:
  dashed_circle: 0.0.1
  url_launcher: ^5.0.3
  fluttertoast: ^3.1.3
  http:
  shared_preferences:
  connectivity:
  provider:
  #flutter_facebook_login: 3.0.0
  geolocator:
  geocoder:
  html:
  clustering_google_maps:
  razorpay_flutter:
  after_layout:
  liquid_pull_to_refresh:
  expandable:
  flutter_custom_clippers:
  livestream:
  sliding_up_panel:
  wave:
  signature:
  folding_cell:
  flutter_fluid_slider:
  liquid_swipe:
  lipsum:
  flutter_colorpicker:
  flutter_localizations:
    sdk: flutter
  rating_bar:
  clippy_flutter: 1.1.1
  flutter_tags: ^0.4.8
  wallet_core: ^0.2.3+8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/integrations/lang/
    - images/app/icons/
    - images/app/
    - images/wallet/
    - images/flags/
    - images/integrations/icons/
    - images/integrations/img/

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

